name: E2E-Testing CI
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} and RoadRunner ${{ matrix.rr }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ 8.2, 8.3, 8.4]
        symfony: [ '6.4.*', '7.0.*', '7.1.*', '7.2.*', '7.3.*']
        rr: ['2024.*','2025.*']

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex
          extensions: opcache,zip,intl,pcntl,sockets,protobuf,grpc

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v3

      - name: Download RoadRunner ${{ matrix.rr }}
        run: ./vendor/bin/rr get-binary  --no-config --no-interaction --filter=${{ matrix.rr }} --no-ansi

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} and RoadRunner ${{ matrix.rr }}
        run: make testing